language: python

python:
  - "3.6"

service:
  - postgresql

before_install:
  - export DATABASE_URL_TEST="postgresql://postgres@localhost/test"
  - export APP_SETTINGS="app.config.TestingConfig"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database test;' -U postgres
  - python manage.py db upgrade

script:
  - nosetests --with-coverage --cover-package=app

after_script:
  - coveralls
